import './globals.css'
import Navbar from './Navbar/Navbar'
import { Lexend } from "next/font/google"

import { Poppins } from '@next/font/google'

export const metadata = {
  title: 'ArtLand',
  description: 'Generated by create next app',
}

const lexend = Lexend({ 
  subsets: ['latin'],
  weight:['300', '400', '600', '700'],
  variable: "--font-lexend"
})

const poppins = Poppins({ 
  subsets: ['latin'],
  weight:['300', '400', '600', '700'],
  variable: "--font-poppins"
})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${lexend.variable} ${poppins.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
