import './globals.css'
import Navbar from './Navbar'
import Landing from './Landing'
import Process from './Process/page'

export const metadata = {
  title: 'ArtLand',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* <Navbar /> */}
        {/* <Landing /> */}
        {children}
        </body>
    </html>
  )
}
